
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/xana43/CodeLyoko-Legacy/issues" #optional

[[mods]] #mandatory

modId="cm" #mandatory

version="${version}" #mandatory

displayName="CodeLyoko:Legacy" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/xana43/CodeLyoko-Legacy/issues" #optional

logoFile="eye-xana.png" #optional

credits="everyone who has contributed" #optional

authors="Xana43(Ultra_Nerd ingame)" #optional


description='''
this is a mod that is meant to be like the show CodeLyoko, this is a port of the same mod that I worked on from 1.12.2'''

