
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/xana43/CodeLyoko-Legacy/issues" #optional
license="All rights reserved"
[[mods]] #mandatory

modId="cm" #mandatory

version="${version}" #mandatory

displayName="CodeLyoko:Legacy" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/xana43/CodeLyoko-Legacy/issues" #optional

logoFile="eye-xana.png" #optional

credits="everyone who has contributed and everyone who made the music present in the mod" #optional

authors="Xana43(Ultra_Nerd ingame)" #optional


description='''
this is a mod that is meant to be like the show CodeLyoko, this is a port of the same mod that I worked on from 1.12.2'''

[[dependencies.cm]] #optional
# the modid of the dependency
    modId="geckolib" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
# The version range of the dependency
    versionRange="[2.0.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.cm]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.15.2-1.2-35.2,)"
    ordering="NONE"
    side="BOTH"

